export const candidate = {
  name: 'ADMIN',
  shortName: 'ADMIN',
  title: 'Belum diisi',
  region: '—',
  party: '—',
  nomorUrut: '—' as any,
  photo: null,
  initials: 'AD',
  runningMate: '',
  elektabilitas: 0,
  elektabilitasDelta: 0,
  targetSuara: 30,
  targetDate: '14 Februari 2029',
  kontestasi: '',
}

export const statsKartu = [
  { label: 'Total Relawan',    value: '0',       delta: 'Belum ada relawan',         trend: 'neutral', color: 'indigo' },
  { label: 'TPS Terpetakan',   value: '0',       delta: 'dari ± 1.800 TPS',          trend: 'neutral', color: 'teal'   },
  { label: 'Dana Tersisa',     value: 'Rp —',    delta: 'Budget belum diset',         trend: 'neutral', color: 'amber'  },
  { label: 'Elektabilitas',    value: '—%',      delta: 'Belum ada survei',           trend: 'neutral', color: 'green'  },
]

export const modulData = [
  { id:'m0',num:'00',name:'Dashboard Master',     desc:'Command center — semua modul dalam satu pandang',      color:'indigo',status:'active', health:100,alerts:0,stats:'10 modul aktif' },
  { id:'m9',num:'09',name:'Profil Calon',          desc:'Identitas, visi misi, program kerja & jadwal kampanye', color:'purple',status:'active', health:0,  alerts:1,stats:'Profil belum lengkap' },
  { id:'m1',num:'01',name:'Relawan & Posko',       desc:'Database, absensi, tugas & broadcast WA',              color:'green', status:'active', health:0,  alerts:3,stats:'0 relawan terdaftar' },
  { id:'m2',num:'02',name:'Pemetaan Pemilih',      desc:'Peta TPS Gorontalo, DPT, segmentasi & canvassing',     color:'sky',   status:'active', health:0,  alerts:2,stats:'0 TPS terpetakan' },
  { id:'m3',num:'03',name:'Kampanye Digital',      desc:'Konten, sosmed, iklan & monitoring sentimen',          color:'pink',  status:'active', health:0,  alerts:1,stats:'0 konten terjadwal' },
  { id:'m4',num:'04',name:'Saksi & Quick Count',   desc:'Penugasan saksi, upload C1, real-time agregasi',       color:'orange',status:'standby',health:100,alerts:0,stats:'Aktif hari-H' },
  { id:'m5',num:'05',name:'Survei & Elektabilitas',desc:'Builder survei, tracking elektabilitas & simulasi',    color:'teal',  status:'active', health:0,  alerts:0,stats:'0 responden' },
  { id:'m6',num:'06',name:'Keuangan & Budget',     desc:'RAB, approval, LPPDK & cost per vote',                color:'amber', status:'active', health:0,  alerts:4,stats:'Budget belum diset' },
  { id:'m7',num:'07',name:'War Room',              desc:'Pusat komando, laporan harian & crisis room',          color:'red',   status:'active', health:100,alerts:2,stats:'0 isu aktif' },
  { id:'m8',num:'08',name:'Konstituen',            desc:'By name by address — DPT, kawan, relasi, potensi',     color:'purple',status:'active', health:0,  alerts:0,stats:'0 konstituen' },
]

export const alerts: any[] = []

export const aktifitasTimeline: any[] = []

export const elektabilitasChart: any[] = []

export const budgetPos: any[] = []

export const kabGorontalo = [
  { id: 'gorut',       name: 'Gorontalo Utara', dpt: 0, tps: 0, est_suara: 0 },
  { id: 'bone',        name: 'Bone Bolango',     dpt: 0, tps: 0, est_suara: 0 },
  { id: 'bonebol',     name: 'Boalemo',          dpt: 0, tps: 0, est_suara: 0 },
  { id: 'pohuwato',    name: 'Pohuwato',          dpt: 0, tps: 0, est_suara: 0 },
  { id: 'gorontalo',   name: 'Kab. Gorontalo',   dpt: 0, tps: 0, est_suara: 0 },
  { id: 'gortalkota',  name: 'Kota Gorontalo',   dpt: 0, tps: 0, est_suara: 0 },
]

export const modulFields: Record<string, { section: string; fields: { name: string; type: string; desc: string }[] }[]> = {
  m9: [
    { section: 'Profil Calon', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID unik kandidat' },
      { name: 'nama_lengkap', type: 'text',        desc: 'Nama lengkap beserta gelar' },
      { name: 'nama_pendek',  type: 'text',        desc: 'Nama singkat untuk display' },
      { name: 'inisial',      type: 'text',        desc: 'Inisial 2 huruf' },
      { name: 'foto_url',     type: 'file',        desc: 'Foto profil resmi' },
      { name: 'partai',       type: 'text',        desc: 'Nama partai politik' },
      { name: 'nomor_urut',   type: 'integer',     desc: 'Nomor urut caleg di partai' },
      { name: 'dapil',        type: 'text',        desc: 'Daerah pemilihan' },
      { name: 'kontestasi',   type: 'text',        desc: 'DPR RI / DPRD Provinsi / DPRD Kab' },
      { name: 'created_at',   type: 'timestamptz', desc: 'Waktu dibuat' },
    ]},
    { section: 'Visi Misi & Program', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID record' },
      { name: 'kandidat_id',  type: 'uuid',        desc: 'Relasi ke profil calon' },
      { name: 'visi',         type: 'text',        desc: 'Pernyataan visi utama' },
      { name: 'misi',         type: 'text[]',      desc: 'Array butir-butir misi' },
      { name: 'program_kerja',type: 'jsonb',       desc: 'Program kerja per sektor' },
    ]},
    { section: 'Jadwal Kampanye', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID kegiatan' },
      { name: 'kandidat_id',  type: 'uuid',        desc: 'Relasi ke profil calon' },
      { name: 'nama_kegiatan',type: 'text',        desc: 'Nama kegiatan kampanye' },
      { name: 'tanggal',      type: 'date',        desc: 'Tanggal pelaksanaan' },
      { name: 'jam_mulai',    type: 'time',        desc: 'Jam mulai kegiatan' },
      { name: 'lokasi',       type: 'text',        desc: 'Nama lokasi / venue' },
      { name: 'koordinat',    type: 'point',       desc: 'Koordinat GPS lokasi' },
      { name: 'jenis',        type: 'enum',        desc: 'Tatap muka / virtual / media' },
      { name: 'status',       type: 'enum',        desc: 'Terjadwal / selesai / batal' },
    ]},
  ],
  m1: [
    { section: 'Data Relawan', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID unik relawan' },
      { name: 'nama',         type: 'text',        desc: 'Nama lengkap relawan' },
      { name: 'nik',          type: 'text',        desc: 'NIK KTP (16 digit)' },
      { name: 'no_hp',        type: 'text',        desc: 'Nomor WhatsApp aktif' },
      { name: 'level',        type: 'enum',        desc: 'Korkot / Korcam / Korkel / Relawan' },
      { name: 'atasan_id',    type: 'uuid',        desc: 'Relasi ke koordinator atasannya' },
      { name: 'kabkota_id',   type: 'text',        desc: 'Kabupaten/Kota penugasan' },
      { name: 'kecamatan',    type: 'text',        desc: 'Kecamatan penugasan' },
      { name: 'kelurahan',    type: 'text',        desc: 'Kelurahan penugasan' },
      { name: 'status',       type: 'enum',        desc: 'Aktif / nonaktif / pending' },
      { name: 'joined_at',    type: 'timestamptz', desc: 'Tanggal bergabung' },
    ]},
    { section: 'Posko', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID posko' },
      { name: 'nama_posko',   type: 'text',        desc: 'Nama posko tim' },
      { name: 'alamat',       type: 'text',        desc: 'Alamat lengkap posko' },
      { name: 'koordinat',    type: 'point',       desc: 'Koordinat GPS posko' },
      { name: 'pic_id',       type: 'uuid',        desc: 'Penanggung jawab posko' },
      { name: 'kapasitas',    type: 'integer',     desc: 'Kapasitas maksimal relawan' },
    ]},
    { section: 'Absensi & Tugas', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID absensi' },
      { name: 'relawan_id',   type: 'uuid',        desc: 'Relasi ke data relawan' },
      { name: 'tanggal',      type: 'date',        desc: 'Tanggal absensi' },
      { name: 'hadir',        type: 'boolean',     desc: 'Status kehadiran' },
      { name: 'tugas',        type: 'text',        desc: 'Deskripsi tugas hari ini' },
      { name: 'lokasi_check', type: 'point',       desc: 'GPS saat check-in QR' },
    ]},
  ],
  m2: [
    { section: 'Data TPS', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID TPS' },
      { name: 'kode_tps',     type: 'text',        desc: 'Kode TPS format KPU' },
      { name: 'nama_tps',     type: 'text',        desc: 'Nama TPS' },
      { name: 'kabkota',      type: 'text',        desc: 'Kabupaten/Kota lokasi TPS' },
      { name: 'kecamatan',    type: 'text',        desc: 'Kecamatan TPS' },
      { name: 'kelurahan',    type: 'text',        desc: 'Kelurahan/Desa TPS' },
      { name: 'koordinat',    type: 'point',       desc: 'Koordinat GPS TPS' },
      { name: 'dpt_count',    type: 'integer',     desc: 'Jumlah pemilih terdaftar (DPT)' },
      { name: 'target_suara', type: 'integer',     desc: 'Target suara di TPS ini' },
      { name: 'saksi_id',     type: 'uuid',        desc: 'Relawan saksi yang ditugaskan' },
    ]},
    { section: 'Data Pemilih (DPT)', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID pemilih' },
      { name: 'tps_id',       type: 'uuid',        desc: 'Relasi ke TPS' },
      { name: 'nama',         type: 'text',        desc: 'Nama pemilih sesuai DPT' },
      { name: 'nik',          type: 'text',        desc: 'NIK KTP' },
      { name: 'jenis_kelamin',type: 'enum',        desc: 'L / P' },
      { name: 'tgl_lahir',    type: 'date',        desc: 'Tanggal lahir pemilih' },
      { name: 'alamat',       type: 'text',        desc: 'Alamat sesuai KTP' },
      { name: 'status_dukungan', type: 'enum',     desc: 'Pendukung / netral / lawan / belum didata' },
      { name: 'canvassed_at', type: 'timestamptz', desc: 'Waktu terakhir dicanvass' },
    ]},
  ],
  m3: [
    { section: 'Konten Kampanye', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID konten' },
      { name: 'judul',        type: 'text',        desc: 'Judul konten' },
      { name: 'platform',     type: 'enum[]',      desc: 'Instagram / TikTok / FB / Twitter / YouTube' },
      { name: 'format',       type: 'enum',        desc: 'Foto / video / carousel / reel / story' },
      { name: 'caption',      type: 'text',        desc: 'Caption siap posting' },
      { name: 'aset_url',     type: 'file[]',      desc: 'File foto/video konten' },
      { name: 'jadwal_post',  type: 'timestamptz', desc: 'Jadwal tayang konten' },
      { name: 'status',       type: 'enum',        desc: 'Draft / review / approved / published' },
      { name: 'dibuat_oleh',  type: 'uuid',        desc: 'User yang membuat konten' },
    ]},
    { section: 'Monitoring Sosmed', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID data monitoring' },
      { name: 'tanggal',      type: 'date',        desc: 'Tanggal monitoring' },
      { name: 'platform',     type: 'enum',        desc: 'Platform yang dimonitor' },
      { name: 'reach',        type: 'bigint',      desc: 'Total jangkauan konten' },
      { name: 'engagement',   type: 'bigint',      desc: 'Total interaksi (like, comment, share)' },
      { name: 'sentimen',     type: 'enum',        desc: 'Positif / netral / negatif' },
    ]},
  ],
  m4: [
    { section: 'Penugasan Saksi', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID penugasan' },
      { name: 'relawan_id',   type: 'uuid',        desc: 'Relawan yang jadi saksi' },
      { name: 'tps_id',       type: 'uuid',        desc: 'TPS yang dijaga' },
      { name: 'status',       type: 'enum',        desc: 'Hadir / belum / tidak hadir' },
      { name: 'check_in_at',  type: 'timestamptz', desc: 'Waktu check-in di TPS' },
    ]},
    { section: 'Upload Form C1', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID upload C1' },
      { name: 'tps_id',       type: 'uuid',        desc: 'TPS asal form C1' },
      { name: 'saksi_id',     type: 'uuid',        desc: 'Saksi yang mengupload' },
      { name: 'foto_c1',      type: 'file[]',      desc: 'Foto form C1 halaman 1 dan 2' },
      { name: 'suara_caleg',  type: 'integer',     desc: 'Suara kandidat dari C1' },
      { name: 'suara_partai', type: 'integer',     desc: 'Total suara partai di TPS' },
      { name: 'ocr_status',   type: 'enum',        desc: 'Pending / proses / selesai / error' },
      { name: 'verified',     type: 'boolean',     desc: 'Sudah diverifikasi tim' },
      { name: 'uploaded_at',  type: 'timestamptz', desc: 'Waktu upload' },
    ]},
  ],
  m5: [
    { section: 'Survei', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID survei' },
      { name: 'judul',        type: 'text',        desc: 'Judul survei' },
      { name: 'pertanyaan',   type: 'jsonb[]',     desc: 'Array pertanyaan + pilihan jawaban' },
      { name: 'target_resp',  type: 'integer',     desc: 'Target jumlah responden' },
      { name: 'wilayah',      type: 'text[]',      desc: 'Wilayah target survei' },
      { name: 'status',       type: 'enum',        desc: 'Draft / aktif / selesai' },
      { name: 'dibuat_at',    type: 'timestamptz', desc: 'Waktu survei dibuat' },
    ]},
    { section: 'Respons Survei', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID respons' },
      { name: 'survei_id',    type: 'uuid',        desc: 'Relasi ke survei' },
      { name: 'responden_nik',type: 'text',        desc: 'NIK responden (opsional)' },
      { name: 'jawaban',      type: 'jsonb',       desc: 'Map pertanyaan → jawaban' },
      { name: 'kabkota',      type: 'text',        desc: 'Kabupaten/Kota responden' },
      { name: 'submitted_at', type: 'timestamptz', desc: 'Waktu pengisian' },
    ]},
  ],
  m6: [
    { section: 'RAB & Budget', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID pos anggaran' },
      { name: 'nama_pos',     type: 'text',        desc: 'Nama pos pengeluaran' },
      { name: 'kategori',     type: 'enum',        desc: 'Operasional / alat peraga / digital / SDM / lainnya' },
      { name: 'anggaran',     type: 'decimal',     desc: 'Pagu anggaran (Rupiah)' },
      { name: 'wilayah',      type: 'text',        desc: 'Kabupaten/Kota alokasi' },
    ]},
    { section: 'Transaksi', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID transaksi' },
      { name: 'pos_id',       type: 'uuid',        desc: 'Relasi ke pos RAB' },
      { name: 'jenis',        type: 'enum',        desc: 'Pemasukan / pengeluaran' },
      { name: 'jumlah',       type: 'decimal',     desc: 'Nominal transaksi (Rupiah)' },
      { name: 'keterangan',   type: 'text',        desc: 'Deskripsi transaksi' },
      { name: 'bukti_url',    type: 'file',        desc: 'Foto struk / bukti transfer' },
      { name: 'disetujui_oleh', type: 'uuid',      desc: 'User yang menyetujui' },
      { name: 'tanggal',      type: 'date',        desc: 'Tanggal transaksi' },
    ]},
  ],
  m7: [
    { section: 'Laporan Harian', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID laporan' },
      { name: 'tanggal',      type: 'date',        desc: 'Tanggal laporan' },
      { name: 'ringkasan',    type: 'text',        desc: 'Ringkasan situasi hari ini' },
      { name: 'isu_utama',    type: 'text[]',      desc: 'Daftar isu/masalah yang muncul' },
      { name: 'tindak_lanjut',type: 'text',        desc: 'Rencana tindak lanjut' },
      { name: 'dibuat_oleh',  type: 'uuid',        desc: 'Pembuat laporan' },
    ]},
    { section: 'Crisis Room', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID insiden' },
      { name: 'judul',        type: 'text',        desc: 'Judul insiden / krisis' },
      { name: 'deskripsi',    type: 'text',        desc: 'Detail kejadian' },
      { name: 'level',        type: 'enum',        desc: 'Info / warning / critical' },
      { name: 'status',       type: 'enum',        desc: 'Open / on-progress / resolved' },
      { name: 'pic_id',       type: 'uuid',        desc: 'Penanggung jawab penanganan' },
      { name: 'created_at',   type: 'timestamptz', desc: 'Waktu insiden dilaporkan' },
      { name: 'resolved_at',  type: 'timestamptz', desc: 'Waktu insiden diselesaikan' },
    ]},
  ],
  m8: [
    { section: 'Data Konstituen', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID konstituen' },
      { name: 'nama',         type: 'text',        desc: 'Nama lengkap' },
      { name: 'nik',          type: 'text',        desc: 'NIK KTP' },
      { name: 'no_hp',        type: 'text',        desc: 'Nomor WhatsApp' },
      { name: 'alamat',       type: 'text',        desc: 'Alamat lengkap' },
      { name: 'kabkota',      type: 'text',        desc: 'Kabupaten/Kota' },
      { name: 'kecamatan',    type: 'text',        desc: 'Kecamatan' },
      { name: 'kelurahan',    type: 'text',        desc: 'Kelurahan/Desa' },
      { name: 'kategori',     type: 'enum',        desc: 'Pemilih / tokoh / kelompok / aspirasi' },
      { name: 'status_crm',   type: 'enum',        desc: 'Baru / terhubung / aktif / dorman' },
    ]},
    { section: 'Aspirasi', fields: [
      { name: 'id',           type: 'uuid',        desc: 'ID aspirasi' },
      { name: 'konstituen_id',type: 'uuid',        desc: 'Relasi ke konstituen' },
      { name: 'isi_aspirasi', type: 'text',        desc: 'Deskripsi aspirasi/keluhan' },
      { name: 'sektor',       type: 'enum',        desc: 'Infrastruktur / pendidikan / kesehatan / ekonomi / lainnya' },
      { name: 'status',       type: 'enum',        desc: 'Masuk / ditindaklanjuti / selesai' },
      { name: 'submitted_at', type: 'timestamptz', desc: 'Waktu aspirasi masuk' },
    ]},
  ],
}
